meta_product_name: "Project_safety"
meta_title: "Project_safety - all aboute safety, more ui ux for everyone"
meta_description: "Project_safety is a open source, a personal project implementing ReactJS and Tailwind
Build from scratch, only for learning propouse, all info and credits to adrianhajdind."
meta_image: "logo_blue.jpg"
twitter_account: "@product_twitter_account"   # required for Twitter Cards